name: GitHub Actions Demo

on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
    
    
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "🚀 Job was triggered by ${{github.event_name}}"
      - run: echo "🔎 The name of the branch is ${{github.ref}}"
      - run: echo "ᢀ Var ${{vars.MY_VAR}}"
      - run: echo "::debug::Writing a debug message..."
      
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "🧪 Testing..."
      - run: echo "ᢀ Var ${{vars.MY_VAR}}"

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          echo "ᢀ Var ${{vars.MY_VAR}}"
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          echo "ᢀ Var ${{vars.MY_VAR}}"
          sleep 10
      - run: |
          echo "🚀 Step 2..."
          sleep 10
      - run: |
          echo "🚀 Step 3..."
          sleep 10
      - run: |
          echo "🚀 Step 4..."
          sleep 10
      - run: |
          echo "🚀 Step 5..."
          sleep 10
